spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bioconversion_db
    username: bioconversion_user
    password: bioconversion_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

logging:
  level:
    com.bioconversion: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG


app:
  commission:
    taux: 0.05  # 5% — valeur à confirmer avec la MOA (CDC §2.2.3, C-MUST-5)